language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install redis-server
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage coveralls --use-mirrors
script: nosetests --with-coverage --cover-package=fakeredis --cover-erase
notifications:
  email:
    - jls.npi@gmail.com
after_success: coveralls
